"""phase 2 business objects

Revision ID: 31869657f4d2
Revises: e9a10d958b0e
Create Date: 2026-10-01 17:04:41.455382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31869657f4d2'
down_revision: Union[str, Sequence[str], None] = 'e9a10d958b0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document',
    sa.Column('item_version_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=128), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.Column('changed_on', sa.DateTime(), nullable=False),
    sa.Column('created_by_fk', sa.Integer(), nullable=True),
    sa.Column('changed_by_fk', sa.Integer(), nullable=True),
    sa.CheckConstraint('file_size IS NULL OR file_size >= 0', name='ck_document_file_size_non_negative'),
    sa.ForeignKeyConstraint(['changed_by_fk'], ['ab_user.id'], ),
    sa.ForeignKeyConstraint(['created_by_fk'], ['ab_user.id'], ),
    sa.ForeignKeyConstraint(['item_version_id'], ['item_version.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('item_version_id')
    )
    op.create_table('part',
    sa.Column('item_version_id', sa.Integer(), nullable=False),
    sa.Column('unit_of_measure_id', sa.Integer(), nullable=False),
    sa.Column('make_buy_code_id', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('weight_uom_id', sa.Integer(), nullable=True),
    sa.Column('material', sa.String(length=128), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.Column('changed_on', sa.DateTime(), nullable=False),
    sa.Column('created_by_fk', sa.Integer(), nullable=True),
    sa.Column('changed_by_fk', sa.Integer(), nullable=True),
    sa.CheckConstraint('weight IS NULL OR weight >= 0', name='ck_part_weight_non_negative'),
    sa.ForeignKeyConstraint(['changed_by_fk'], ['ab_user.id'], ),
    sa.ForeignKeyConstraint(['created_by_fk'], ['ab_user.id'], ),
    sa.ForeignKeyConstraint(['item_version_id'], ['item_version.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['make_buy_code_id'], ['make_buy_code.id'], ),
    sa.ForeignKeyConstraint(['unit_of_measure_id'], ['unit_of_measure.id'], ),
    sa.ForeignKeyConstraint(['weight_uom_id'], ['unit_of_measure.id'], ),
    sa.PrimaryKeyConstraint('item_version_id')
    )
    op.create_table('product',
    sa.Column('item_version_id', sa.Integer(), nullable=False),
    sa.Column('product_family_id', sa.Integer(), nullable=True),
    sa.Column('market_id', sa.Integer(), nullable=True),
    sa.Column('platform', sa.String(length=128), nullable=True),
    sa.Column('release_target', sa.Date(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.Column('changed_on', sa.DateTime(), nullable=False),
    sa.Column('created_by_fk', sa.Integer(), nullable=True),
    sa.Column('changed_by_fk', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['changed_by_fk'], ['ab_user.id'], ),
    sa.ForeignKeyConstraint(['created_by_fk'], ['ab_user.id'], ),
    sa.ForeignKeyConstraint(['item_version_id'], ['item_version.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['market_id'], ['market.id'], ),
    sa.ForeignKeyConstraint(['product_family_id'], ['product_family.id'], ),
    sa.PrimaryKeyConstraint('item_version_id')
    )
    op.create_table('requirement',
    sa.Column('item_version_id', sa.Integer(), nullable=False),
    sa.Column('requirement_text', sa.Text(), nullable=False),
    sa.Column('verification_method_id', sa.Integer(), nullable=True),
    sa.Column('priority_code_id', sa.Integer(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.Column('changed_on', sa.DateTime(), nullable=False),
    sa.Column('created_by_fk', sa.Integer(), nullable=True),
    sa.Column('changed_by_fk', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['changed_by_fk'], ['ab_user.id'], ),
    sa.ForeignKeyConstraint(['created_by_fk'], ['ab_user.id'], ),
    sa.ForeignKeyConstraint(['item_version_id'], ['item_version.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['priority_code_id'], ['priority_code.id'], ),
    sa.ForeignKeyConstraint(['verification_method_id'], ['verification_method.id'], ),
    sa.PrimaryKeyConstraint('item_version_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('requirement')
    op.drop_table('product')
    op.drop_table('part')
    op.drop_table('document')
    # ### end Alembic commands ###
