"""phase 7 baseline

Revision ID: 5597f1a0f266
Revises: 31869657f4d2
Create Date: 2026-10-01 17:22:17.126764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5597f1a0f266'
down_revision: Union[str, Sequence[str], None] = '31869657f4d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('baseline',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('baseline_number', sa.String(length=32), nullable=False),
    sa.Column('baseline_name', sa.String(length=128), nullable=False),
    sa.Column('product_version_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('frozen_at', sa.DateTime(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.Column('changed_on', sa.DateTime(), nullable=False),
    sa.Column('created_by_fk', sa.Integer(), nullable=True),
    sa.Column('changed_by_fk', sa.Integer(), nullable=True),
    sa.CheckConstraint("(status = 'FROZEN' AND frozen_at IS NOT NULL) OR (status = 'DRAFT' AND frozen_at IS NULL)", name='ck_baseline_frozen_consistency'),
    sa.CheckConstraint("status IN ('DRAFT', 'FROZEN')", name='ck_baseline_status'),
    sa.ForeignKeyConstraint(['changed_by_fk'], ['ab_user.id'], ),
    sa.ForeignKeyConstraint(['created_by_fk'], ['ab_user.id'], ),
    sa.ForeignKeyConstraint(['product_version_id'], ['item_version.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('baseline_number', name='uq_baseline_number')
    )
    op.create_table('baseline_member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('baseline_id', sa.Integer(), nullable=False),
    sa.Column('item_version_id', sa.Integer(), nullable=False),
    sa.Column('parent_member_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('find_number', sa.String(length=32), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.Column('changed_on', sa.DateTime(), nullable=False),
    sa.Column('created_by_fk', sa.Integer(), nullable=True),
    sa.Column('changed_by_fk', sa.Integer(), nullable=True),
    sa.CheckConstraint('quantity IS NULL OR quantity > 0', name='ck_baseline_member_quantity_positive'),
    sa.ForeignKeyConstraint(['baseline_id'], ['baseline.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['changed_by_fk'], ['ab_user.id'], ),
    sa.ForeignKeyConstraint(['created_by_fk'], ['ab_user.id'], ),
    sa.ForeignKeyConstraint(['item_version_id'], ['item_version.id'], ),
    sa.ForeignKeyConstraint(['parent_member_id'], ['baseline_member.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('baseline_id', 'item_version_id', 'parent_member_id', name='uq_baseline_member')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('baseline_member')
    op.drop_table('baseline')
    # ### end Alembic commands ###
