"""phase 1 core schema

Revision ID: e9a10d958b0e
Revises: 
Create Date: 2026-10-01 17:01:45.397842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9a10d958b0e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ab_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('label', sa.String(length=150), nullable=True),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('ab_permission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('ab_register_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=False),
    sa.Column('last_name', sa.String(length=64), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('password', sa.String(length=256), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('registration_date', sa.DateTime(), nullable=True),
    sa.Column('registration_hash', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('ab_role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('ab_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=False),
    sa.Column('last_name', sa.String(length=64), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('password', sa.String(length=256), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('login_count', sa.Integer(), nullable=True),
    sa.Column('fail_login_count', sa.Integer(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('changed_on', sa.DateTime(), nullable=True),
    sa.Column('created_by_fk', sa.Integer(), nullable=True),
    sa.Column('changed_by_fk', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['changed_by_fk'], ['ab_user.id'], ),
    sa.ForeignKeyConstraint(['created_by_fk'], ['ab_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('ab_view_menu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('ab_api_key',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('key_hash', sa.String(length=256), nullable=False),
    sa.Column('lookup_hash', sa.String(length=256), nullable=True),
    sa.Column('key_prefix', sa.String(length=16), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('scopes', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('expires_on', sa.DateTime(), nullable=True),
    sa.Column('revoked_on', sa.DateTime(), nullable=True),
    sa.Column('last_used_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['ab_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lookup_hash'),
    sa.UniqueConstraint('uuid')
    )
    with op.batch_alter_table('ab_api_key', schema=None) as batch_op:
        batch_op.create_index('idx_api_key_lookup_hash', ['lookup_hash'], unique=True)
        batch_op.create_index('idx_api_key_prefix', ['key_prefix'], unique=False)
        batch_op.create_index('idx_api_key_user_id', ['user_id'], unique=False)

    op.create_table('ab_group_role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['ab_group.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['ab_role.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'role_id')
    )
    with op.batch_alter_table('ab_group_role', schema=None) as batch_op:
        batch_op.create_index('idx_group_id', ['group_id'], unique=False)
        batch_op.create_index('idx_group_role_id', ['role_id'], unique=False)

    op.create_table('ab_permission_view',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.Column('view_menu_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['ab_permission.id'], ),
    sa.ForeignKeyConstraint(['view_menu_id'], ['ab_view_menu.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('permission_id', 'view_menu_id')
    )
    with op.batch_alter_table('ab_permission_view', schema=None) as batch_op:
        batch_op.create_index('idx_permission_id', ['permission_id'], unique=False)
        batch_op.create_index('idx_view_menu_id', ['view_menu_id'], unique=False)

    op.create_table('ab_user_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['ab_group.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['ab_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'group_id')
    )
    with op.batch_alter_table('ab_user_group', schema=None) as batch_op:
        batch_op.create_index('idx_user_group_id', ['group_id'], unique=False)
        batch_op.create_index('idx_user_id', ['user_id'], unique=False)

    op.create_table('ab_user_role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['ab_role.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['ab_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'role_id')
    )
    op.create_table('item_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.Column('changed_on', sa.DateTime(), nullable=False),
    sa.Column('created_by_fk', sa.Integer(), nullable=True),
    sa.Column('changed_by_fk', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['changed_by_fk'], ['ab_user.id'], ),
    sa.ForeignKeyConstraint(['created_by_fk'], ['ab_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_item_type_code')
    )
    op.create_table('lifecycle_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('is_terminal', sa.Boolean(), nullable=False),
    sa.Column('is_releasable', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.Column('changed_on', sa.DateTime(), nullable=False),
    sa.Column('created_by_fk', sa.Integer(), nullable=True),
    sa.Column('changed_by_fk', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['changed_by_fk'], ['ab_user.id'], ),
    sa.ForeignKeyConstraint(['created_by_fk'], ['ab_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_lifecycle_state_code')
    )
    op.create_table('make_buy_code',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.Column('changed_on', sa.DateTime(), nullable=False),
    sa.Column('created_by_fk', sa.Integer(), nullable=True),
    sa.Column('changed_by_fk', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['changed_by_fk'], ['ab_user.id'], ),
    sa.ForeignKeyConstraint(['created_by_fk'], ['ab_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_make_buy_code_code')
    )
    op.create_table('market',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.Column('changed_on', sa.DateTime(), nullable=False),
    sa.Column('created_by_fk', sa.Integer(), nullable=True),
    sa.Column('changed_by_fk', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['changed_by_fk'], ['ab_user.id'], ),
    sa.ForeignKeyConstraint(['created_by_fk'], ['ab_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_market_code')
    )
    op.create_table('priority_code',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.Column('changed_on', sa.DateTime(), nullable=False),
    sa.Column('created_by_fk', sa.Integer(), nullable=True),
    sa.Column('changed_by_fk', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['changed_by_fk'], ['ab_user.id'], ),
    sa.ForeignKeyConstraint(['created_by_fk'], ['ab_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_priority_code_code')
    )
    op.create_table('product_family',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.Column('changed_on', sa.DateTime(), nullable=False),
    sa.Column('created_by_fk', sa.Integer(), nullable=True),
    sa.Column('changed_by_fk', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['changed_by_fk'], ['ab_user.id'], ),
    sa.ForeignKeyConstraint(['created_by_fk'], ['ab_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_product_family_code')
    )
    op.create_table('relationship_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('is_structural', sa.Boolean(), nullable=False),
    sa.Column('allows_quantity', sa.Boolean(), nullable=False),
    sa.Column('allows_find_number', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.Column('changed_on', sa.DateTime(), nullable=False),
    sa.Column('created_by_fk', sa.Integer(), nullable=True),
    sa.Column('changed_by_fk', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['changed_by_fk'], ['ab_user.id'], ),
    sa.ForeignKeyConstraint(['created_by_fk'], ['ab_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_relationship_type_code')
    )
    op.create_table('unit_of_measure',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.Column('changed_on', sa.DateTime(), nullable=False),
    sa.Column('created_by_fk', sa.Integer(), nullable=True),
    sa.Column('changed_by_fk', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['changed_by_fk'], ['ab_user.id'], ),
    sa.ForeignKeyConstraint(['created_by_fk'], ['ab_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_unit_of_measure_code')
    )
    op.create_table('verification_method',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.Column('changed_on', sa.DateTime(), nullable=False),
    sa.Column('created_by_fk', sa.Integer(), nullable=True),
    sa.Column('changed_by_fk', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['changed_by_fk'], ['ab_user.id'], ),
    sa.ForeignKeyConstraint(['created_by_fk'], ['ab_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_verification_method_code')
    )
    op.create_table('ab_permission_view_role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('permission_view_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['permission_view_id'], ['ab_permission_view.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['ab_role.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('permission_view_id', 'role_id')
    )
    with op.batch_alter_table('ab_permission_view_role', schema=None) as batch_op:
        batch_op.create_index('idx_permission_view_id', ['permission_view_id'], unique=False)
        batch_op.create_index('idx_role_id', ['role_id'], unique=False)

    op.create_table('item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_type_id', sa.Integer(), nullable=False),
    sa.Column('item_number', sa.String(length=64), nullable=False),
    sa.Column('current_version_id', sa.Integer(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.Column('changed_on', sa.DateTime(), nullable=False),
    sa.Column('created_by_fk', sa.Integer(), nullable=True),
    sa.Column('changed_by_fk', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['changed_by_fk'], ['ab_user.id'], ),
    sa.ForeignKeyConstraint(['created_by_fk'], ['ab_user.id'], ),
    sa.ForeignKeyConstraint(['current_version_id'], ['item_version.id'], name='fk_item_current_version_id', ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['item_type_id'], ['item_type.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_type_id', 'item_number', name='uq_item_type_number')
    )
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.create_index('ix_item_current_version', ['current_version_id'], unique=False)

    op.create_table('lifecycle_transition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_state_id', sa.Integer(), nullable=False),
    sa.Column('to_state_id', sa.Integer(), nullable=False),
    sa.Column('required_role_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.Column('changed_on', sa.DateTime(), nullable=False),
    sa.Column('created_by_fk', sa.Integer(), nullable=True),
    sa.Column('changed_by_fk', sa.Integer(), nullable=True),
    sa.CheckConstraint('from_state_id <> to_state_id', name='ck_lifecycle_transition_distinct'),
    sa.ForeignKeyConstraint(['changed_by_fk'], ['ab_user.id'], ),
    sa.ForeignKeyConstraint(['created_by_fk'], ['ab_user.id'], ),
    sa.ForeignKeyConstraint(['from_state_id'], ['lifecycle_state.id'], ),
    sa.ForeignKeyConstraint(['required_role_id'], ['ab_role.id'], ),
    sa.ForeignKeyConstraint(['to_state_id'], ['lifecycle_state.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('from_state_id', 'to_state_id', name='uq_lifecycle_transition_edge')
    )
    op.create_table('audit_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('from_value', sa.String(length=255), nullable=True),
    sa.Column('to_value', sa.String(length=255), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.Column('changed_on', sa.DateTime(), nullable=False),
    sa.Column('created_by_fk', sa.Integer(), nullable=True),
    sa.Column('changed_by_fk', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['changed_by_fk'], ['ab_user.id'], ),
    sa.ForeignKeyConstraint(['created_by_fk'], ['ab_user.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_event', schema=None) as batch_op:
        batch_op.create_index('ix_audit_event_entity', ['entity_type', 'entity_id'], unique=False)
        batch_op.create_index('ix_audit_event_item', ['item_id', 'created_on'], unique=False)

    op.create_table('item_version',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('version_sequence', sa.Integer(), nullable=False),
    sa.Column('major_revision', sa.Integer(), nullable=False),
    sa.Column('minor_revision', sa.Integer(), nullable=False),
    sa.Column('revision_label', sa.String(length=16), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('lifecycle_state_id', sa.Integer(), nullable=False),
    sa.Column('superseded_by_id', sa.Integer(), nullable=True),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.Column('changed_on', sa.DateTime(), nullable=False),
    sa.Column('created_by_fk', sa.Integer(), nullable=True),
    sa.Column('changed_by_fk', sa.Integer(), nullable=True),
    sa.CheckConstraint('effective_to IS NULL OR effective_from IS NULL OR effective_to >= effective_from', name='ck_item_version_effective_range'),
    sa.CheckConstraint('major_revision >= 0', name='ck_item_version_major_non_negative'),
    sa.CheckConstraint('minor_revision >= 0', name='ck_item_version_minor_non_negative'),
    sa.CheckConstraint('version_sequence >= 1', name='ck_item_version_sequence_positive'),
    sa.ForeignKeyConstraint(['changed_by_fk'], ['ab_user.id'], ),
    sa.ForeignKeyConstraint(['created_by_fk'], ['ab_user.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lifecycle_state_id'], ['lifecycle_state.id'], ),
    sa.ForeignKeyConstraint(['superseded_by_id'], ['item_version.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_id', 'major_revision', 'minor_revision', name='uq_item_version_revision'),
    sa.UniqueConstraint('item_id', 'version_sequence', name='uq_item_version_sequence')
    )
    with op.batch_alter_table('item_version', schema=None) as batch_op:
        batch_op.create_index('ix_item_version_lifecycle_state', ['lifecycle_state_id'], unique=False)

    op.create_table('item_relationship',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('relationship_type_id', sa.Integer(), nullable=False),
    sa.Column('source_item_version_id', sa.Integer(), nullable=False),
    sa.Column('target_item_version_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('find_number', sa.String(length=32), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.Column('changed_on', sa.DateTime(), nullable=False),
    sa.Column('created_by_fk', sa.Integer(), nullable=True),
    sa.Column('changed_by_fk', sa.Integer(), nullable=True),
    sa.CheckConstraint('quantity IS NULL OR quantity > 0', name='ck_item_relationship_quantity_positive'),
    sa.CheckConstraint('source_item_version_id <> target_item_version_id', name='ck_item_relationship_no_self'),
    sa.ForeignKeyConstraint(['changed_by_fk'], ['ab_user.id'], ),
    sa.ForeignKeyConstraint(['created_by_fk'], ['ab_user.id'], ),
    sa.ForeignKeyConstraint(['relationship_type_id'], ['relationship_type.id'], ),
    sa.ForeignKeyConstraint(['source_item_version_id'], ['item_version.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_item_version_id'], ['item_version.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('relationship_type_id', 'source_item_version_id', 'target_item_version_id', name='uq_item_relationship_edge')
    )
    with op.batch_alter_table('item_relationship', schema=None) as batch_op:
        batch_op.create_index('ix_item_relationship_source', ['source_item_version_id'], unique=False)
        batch_op.create_index('ix_item_relationship_target', ['target_item_version_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item_relationship', schema=None) as batch_op:
        batch_op.drop_index('ix_item_relationship_target')
        batch_op.drop_index('ix_item_relationship_source')

    op.drop_table('item_relationship')
    with op.batch_alter_table('item_version', schema=None) as batch_op:
        batch_op.drop_index('ix_item_version_lifecycle_state')

    op.drop_table('item_version')
    with op.batch_alter_table('audit_event', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_event_item')
        batch_op.drop_index('ix_audit_event_entity')

    op.drop_table('audit_event')
    op.drop_table('lifecycle_transition')
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_index('ix_item_current_version')

    op.drop_table('item')
    with op.batch_alter_table('ab_permission_view_role', schema=None) as batch_op:
        batch_op.drop_index('idx_role_id')
        batch_op.drop_index('idx_permission_view_id')

    op.drop_table('ab_permission_view_role')
    op.drop_table('verification_method')
    op.drop_table('unit_of_measure')
    op.drop_table('relationship_type')
    op.drop_table('product_family')
    op.drop_table('priority_code')
    op.drop_table('market')
    op.drop_table('make_buy_code')
    op.drop_table('lifecycle_state')
    op.drop_table('item_type')
    op.drop_table('ab_user_role')
    with op.batch_alter_table('ab_user_group', schema=None) as batch_op:
        batch_op.drop_index('idx_user_id')
        batch_op.drop_index('idx_user_group_id')

    op.drop_table('ab_user_group')
    with op.batch_alter_table('ab_permission_view', schema=None) as batch_op:
        batch_op.drop_index('idx_view_menu_id')
        batch_op.drop_index('idx_permission_id')

    op.drop_table('ab_permission_view')
    with op.batch_alter_table('ab_group_role', schema=None) as batch_op:
        batch_op.drop_index('idx_group_role_id')
        batch_op.drop_index('idx_group_id')

    op.drop_table('ab_group_role')
    with op.batch_alter_table('ab_api_key', schema=None) as batch_op:
        batch_op.drop_index('idx_api_key_user_id')
        batch_op.drop_index('idx_api_key_prefix')
        batch_op.drop_index('idx_api_key_lookup_hash')

    op.drop_table('ab_api_key')
    op.drop_table('ab_view_menu')
    op.drop_table('ab_user')
    op.drop_table('ab_role')
    op.drop_table('ab_register_user')
    op.drop_table('ab_permission')
    op.drop_table('ab_group')
    # ### end Alembic commands ###
